AllCops:
  Exclude:
    - "bin/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/spec_helper.rb"
    - "gems/*"
    - "Rakefile"
    - "tooling/*"
  NewCops: disable
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 130

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - "Gemfile*"
    - "*.gemspec"
    - "spec/**/*"

Naming/FileName:
  Exclude:
    - "lib/scout_apm/scout_apm_logging.rb"
    - "spec/scout_apm_logging_spec.rb"

Style/Documentation:
  Enabled: true

Naming/PredicateName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Lint/LiteralAsCondition:
  Enabled: false

Layout/LineLength:
  Max: 130

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': "[]"
    '%W': "[]"
