# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/resource/v1/resource.proto

require 'google/protobuf'

require_relative '../../common/v1/common_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("scout/opentelemetry/proto/resource/v1/resource.proto", :syntax => :proto3) do
    add_message "scout_apm.logging.loggers.opentelemetry.proto.resource.v1.Resource" do
      repeated :attributes, :message, 1, "scout_apm.logging.loggers.opentelemetry.proto.common.v1.KeyValue"
      optional :dropped_attributes_count, :uint32, 2
    end
  end
end

module ScoutApm
  module Logging
    module Loggers
      module Opentelemetry
        module Proto
          module Resource
            module V1
              Resource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("scout_apm.logging.loggers.opentelemetry.proto.resource.v1.Resource").msgclass
            end
          end
        end
      end
    end
  end
end
